name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-04"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "90b09e2f34944a2b907004dae2a515d3"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "84baf0ae-c8c5-413b-a13c-fcfced123eba"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/iwansaja/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/iwansaja/Siren/refs/heads/master/web/sub.html"
